# Generated by Django 3.2.4 on 2022-11-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_storage_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dst',
        ),
    ]
