# Generated by Django 3.2.4 on 2022-11-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_storage_App', '0002_delete_dst'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=87)),
                ('age', models.IntegerField()),
                ('area', models.CharField(max_length=117)),
                ('gender', models.CharField(max_length=11)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
